package com.app.cheffyuser.utils

object Constants {

    const val PREF_ACCESS_TOKEN = "PREF_ACCESS_TOKEN"
    const val PREF_REFRESH_TOKEN = "PREF_REFRESH_TOKEN"
    const val PREF_PHONE_NUMBER = "PREF_PHONE_NUMBER"

    const val PREF_USER_ISLOGIN = "PREF_USER_ISLOGIN"
    const val PREF_USER_NAME = "PREF_USER_NAME"
    const val PREF_USER_EMAIL = "PREF_USER_EMAIL"
    const val PREF_USER_PIC = "PREF_USER_PIC"
    const val PHONE_VERIFIED = "PHONE_VERIFIED_AT"

    const val PREF_FIRST_RUN = "PREF_FIRST_RUN"

    const val PREF_IS_DEFAULT_LOC_SET = "PREF_IS_DEFAULT_LOC_SET"
    const val PREF_DEFAULT_LAT = "PREF_DEFAULT_LAT"
    const val PREF_DEFAULT_LON = "PREF_DEFAULT_LON"
    const val PREF_DEFAULT_ADDRESS = "PREF_DEFAULT_ADDRESS"
    const val PREF_DEFAULT_PRITXT = "PREF_DEFAULT_PRITXT"
    const val PREF_DEFAULT_SECTXT = "PREF_DEFAULT_SECTXT"

    const val PREF_CURRENT_LOCATION = "PREF_CURRENT_LOCATION"
    const val PREF_CURRENT_LAT = "PREF_CURRENT_LAT"
    const val PREF_CURRENT_LON = "PREF_CURRENT_LON"
    const val PREF_CURRENT_ADDRESS = "PREF_CURRENT_ADDRESS"

    const val PREF_LAST_LOCATION = "PREF_LAST_LOCATION"
    const val PREF_LAST_LAT = "PREF_LAST_LAT"
    const val PREF_LAST_LON = "PREF_LAST_LON"
    const val PREF_LAST_ADDRESS = "PREF_LAST_ADDRESS"

    const val PREF_FIREBASE_TOKEN = "PREF_FIREBASE_TOKEN"
    const val PREF_LAUNCH_TIMES = "PREF_LAUNCH_TIMES"
    const val PREF_APP_VERSION = "PREF_APP_VERSION"

    //intent extras
    const val PLATES_RESPONSE_EXTRA = "PLATES_RESPONSE_EXTRA"

    //parsed to gson classes
    const val PREF_USER_DATA_CLASS = "PREF_USER_DATA_CLASS"
    const val PREF_FULLUSER_DATA_CLASS = "PREF_FULLUSER_DATA_CLASS"
    const val PREF_USER_SHIPPING_CLASS = "PREF_USER_SHIPPING_CLASS"


}
